# This is a basic workflow to help you get started with Actions

name: Auto sync

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Fork Sync
  # You may pin to the exact commit or the version.
  # uses: tgymnich/fork-sync@0cc6ac48fd51415e7c34e5b8823021bc952a5f5f
        uses: tgymnich/fork-sync@v1.2.1
        with:
         # Owner of the forked repository
          owner: genshinmap # optional
         # Token for the github API
          github_token: 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
         # Branch to track
          head: develop # optional, default is master
          # Branch to keep updated
          base: develop # optional, default is master
